brew "stow"
brew "fish"
brew "neovim"
brew "node"
brew "tmux"
brew "mosh"
brew "clipper", restart_service: true
brew "git-delta"
brew "fzf"
brew "ripgrep"
brew "fd"

cask "alacritty"
cask "font-jetbrains-mono-nerd-font"
cask "karabiner-elements"
